name: Test-Octokit
on:
  push:
    branches:
      - main    
#  pull_request:
    # branches:
      # - main
#     # Only following types are handled by the action, but one can default to all as well
#   types: [opened, reopened, synchronize]
jobs:
  Create-PR:
    runs-on: ubuntu-latest
    steps:

      - name: Try rest calls
        uses: actions/github-script@v6
        with:
          script: |
           github.rest.pulls.create({
            owner: 'githubappuser',
            repo: 'Release-testing',
            title: 'Try octokit',
            head: 'main',
            base: 'test',
            })
      - name: Run checks
        uses: ./.github/workflows/sampleTest-1.yml
          # ./.github/workflows/sampleTest-2.yml
          # ./.github/workflows/sampleTest-3.yml
#       - name: Check action status
#         uses: actions/github-script@v6
#         if: ${{ !failure() }}