name: Test-Octokit
on:
  push:
    branches:
      - main    
#  pull_request:
    # branches:
      # - main
#     # Only following types are handled by the action, but one can default to all as well
#   types: [opened, reopened, synchronize]
jobs:
  Create-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Get Pull Request Number
        id: pr
        run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
        env:
          GITHUB_TOKEN: ${{ secrets.OCTOKIT_TEST }}
      - name: Try rest calls
        uses: actions/github-script@v6        
        with:
          github-token: ${{ secrets.OCTOKIT_TEST }}
          script: |
           // const core = require('@actions/core')
           // const prNumber = context.payload.number;
           // core.exportVariable('PULL_NUMBER', prNumber);
           github.rest.pulls.create({
            owner: 'githubappuser',
            repo: 'Release-testing',
            title: '${{ steps.pr.outputs.pull_request_number }}',
            head: 'main',
            base: 'test',
            })