name: Test-Octokit
on:
  push:
    branches:
      - main    
#  pull_request:
    # branches:
      # - main
#     # Only following types are handled by the action, but one can default to all as well
#   types: [opened, reopened, synchronize]
jobs:
  Create-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Try rest calls
        uses: actions/github-script@v6        
        with:
          github-token: ${{ secrets.OCTOKIT_TEST }}
          script: |
           github.rest.pulls.create({
            owner: 'githubappuser',
            repo: 'Release-testing',
            title: 'try getting PR number',
            head: 'main',
            base: 'test',
            })
           const prNumber = github.event.pull_request.head.ref;
           core.exportVariable('PULL_NUMBER', prNumber);
           //console.log(context)