name: Test-Octokit
on:
  push:
    branches:
      - main    
#  pull_request:
    # branches:
      # - main
#     # Only following types are handled by the action, but one can default to all as well
#   types: [opened, reopened, synchronize]
jobs:
  Create-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Get Pull Request Number
        id: pr
        run:   echo ::set-env name=PULL_NUMBER::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Try rest calls
        uses: actions/github-script@v6        
        with:
          github-token: ${{ secrets.OCTOKIT_TEST }}
          script: |
           // const core = require('@actions/core')
           // const prNumber = context.payload.number;
           // core.exportVariable('PULL_NUMBER', prNumber);
           github.rest.pulls.create({
            owner: 'githubappuser',
            repo: 'Release-testing',
            title: '${{ steps.pr.env.pull_request_number }}',
            head: 'main',
            base: 'test',
            })