name: Sample Test 2
on: 
  pull_request:
    types: [opened, reopened]
jobs:
  build-2:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: ls
      - name: Second Step
        run: sleep 50
      - name: Third Step
        run: pwd
