name: Sample Test 3
on: 
  pull_request:
   branches:
     - test
jobs:
  build-3:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: ls
      # - name: Second Step
      #   run: sleep 45
      # - name: Third Step
      #   run: xyz

