name: Sample Test 1
on: 
  push:
  pull_request:
    branches:
      - test
jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: ls
      - name: Second Step
        run: sleep 20
      - name: Third Step
        run: pwd
