name: Sample Test 3
on: 
  pull_request:
    types: [opened, reopened]
  workflow_call:
jobs:
  build-3:
    runs-on: self-hosted
    steps:
      - name: First Step
        run: ls
      - name: Second Step
        run: sleep 45
      - name: Third Step
        run: xyz

