name: Sample Test 1
on: 
  pull_request:
    branches:
      - test
jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - name: Try rest calls
        uses: actions/github-script@v6        
        with:
          github-token: ${{ secrets.OCTOKIT_TEST }}
          script: | 
           const prNumber = ${{github.event.number}} ;
           core.exportVariable('PULL_NUMBER', prNumber);
           console.log(${{github.event.number}})
#use .env folder and use process.env.var to use it dynamically           